# Generated by Django 5.0.4 on 2024-04-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_user_company_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
