# Generated by Django 5.0.4 on 2024-05-07 13:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_company_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logsources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
