# Generated by Django 5.0.4 on 2024-05-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_remove_user_company_user_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
