# Generated by Django 5.0.4 on 2024-05-29 14:03

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_otp_user_otp_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_method',
            field=models.CharField(choices=[('email', 'Email'), ('totp', 'TOTP')], default='totp', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default=pyotp.random_base32, max_length=32),
        ),
    ]
