# Generated by Django 5.0.4 on 2024-05-29 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_otp_method_user_totp_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_method',
            new_name='otpMethod',
        ),
    ]
