# Generated by Django 5.0.4 on 2024-05-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_user_otpmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firstTime',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='otpMethod',
            field=models.CharField(choices=[('email', 'Email'), ('totp', 'TOTP')], default='totp', max_length=10),
        ),
    ]
