# Generated by Django 5.0.4 on 2024-05-29 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_user_firsttime_alter_user_otpmethod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='firstTime',
            new_name='showTotp',
        ),
    ]
