# Generated by Django 5.0.4 on 2024-05-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0003_alter_usecase_components_alter_usecase_datasources_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usecase',
            name='platforms',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='subtechniques',
            field=models.CharField(blank=True, max_length=3000, null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='url',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='mid',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
