# Generated by Django 5.0.4 on 2024-05-02 12:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0004_usecase_platforms_usecase_subtechniques_usecase_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='platforms',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='subtechniques',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
