# Generated by Django 5.0.4 on 2024-05-07 11:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0005_alter_usecase_platforms_alter_usecase_subtechniques'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usecase',
            old_name='cncs',
            new_name='cncsType',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='mid',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='subtechniques',
        ),
        migrations.RemoveField(
            model_name='usecase',
            name='tactics',
        ),
        migrations.AddField(
            model_name='usecase',
            name='logsources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='usecase',
            name='techniques',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
