# Generated by Django 5.0.4 on 2024-05-07 11:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0007_remove_usecase_components_remove_usecase_datasources_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='techniques',
        ),
        migrations.AddField(
            model_name='usecase',
            name='PhaseTasks',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='usecase',
            name='attackVectors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='usecase',
            name='cncsClass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='mitreTechniques',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='usecase',
            name='playbook',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usecase',
            name='rules',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
