# Generated by Django 5.0.4 on 2024-05-07 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0008_remove_usecase_techniques_usecase_phasetasks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usecase',
            old_name='mitigations',
            new_name='mitigation',
        ),
    ]
