# Generated by Django 5.0.4 on 2024-05-07 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0009_rename_mitigations_usecase_mitigation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usecase',
            name='logsources',
        ),
    ]
