# Generated by Django 5.0.4 on 2024-05-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0011_rename_phasetasks_usecase_phasetasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='playbook',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
