# Generated by Django 5.0.4 on 2024-05-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0012_alter_usecase_playbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='mitigation',
            field=models.CharField(blank=True, max_length=100000, null=True),
        ),
    ]
