# Generated by Django 5.0.4 on 2024-05-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0013_alter_usecase_mitigation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='cncsClass',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='cncsType',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='description',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
        migrations.AlterField(
            model_name='usecase',
            name='mitigation',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
