# Generated by Django 5.0.4 on 2024-05-16 14:39

import usecases.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usecases', '0014_alter_usecase_cncsclass_alter_usecase_cncstype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usecase',
            name='playbook',
            field=models.ImageField(blank=True, null=True, upload_to=usecases.models.upload_to),
        ),
    ]
