version: '3.8'

services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwertyadmin
    ports:
      - "5432:5432"
    expose:
      - "5432"
    networks:
      - webapp-network

  django:
    image: django-app:latest
    build:
      context: .
      dockerfile: /backend/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - webapp-network

  angular:
    image: angular-app:latest
    build:
      context: .
      dockerfile: /frontend/Dockerfile
    ports:
      - "80:80"
    networks:
      - webapp-network

networks:
  webapp-network:
    driver: bridge
