# Generated by Django 5.0.4 on 2024-05-08 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rule',
        ),
        migrations.AddField(
            model_name='rulemodel',
            name='syntax',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='rulemodel',
            name='title',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='rulemodel',
            name='type',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='rulemodel',
            name='useCaseId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rulemodel',
            name='ruleCode',
            field=models.CharField(null=True),
        ),
    ]
