# Generated by Django 5.0.4 on 2024-05-08 15:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_delete_rule_rulemodel_syntax_rulemodel_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulemodel',
            name='logsources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
