# Generated by Django 5.0.4 on 2024-05-09 12:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_rulemodel_logsources'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruleModel', models.IntegerField(null=True)),
                ('ruleCode', models.CharField(null=True)),
                ('logsources', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, null=True), blank=True, null=True, size=None)),
            ],
        ),
    ]
