# Generated by Django 5.0.4 on 2024-05-09 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='ruleModel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rules.rulemodel'),
        ),
    ]
