# Generated by Django 5.0.4 on 2024-05-09 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_company_logsources'),
        ('rules', '0005_alter_rule_rulemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company'),
        ),
    ]
