# Generated by Django 5.0.4 on 2024-05-22 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0006_rule_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rulemodel',
            name='syntax',
        ),
        migrations.AddField(
            model_name='rule',
            name='syntax',
            field=models.CharField(null=True),
        ),
    ]
