# Generated by Django 5.0.4 on 2024-05-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_remove_rulemodel_syntax_rule_syntax'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisteredLogSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(null=True)),
                ('description', models.CharField(null=True)),
            ],
        ),
    ]
